### ISSUE TITLE
Wrong  height displayed  in QMS 1.16.0

### ISSUE THREAD

**Issue by konrad555** [Maproom/qmapshack#438]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

I am using 10m Digital Elevation Modell (DEM) Austria: 
https://www.data.gv.at/katalog/dataset/land-ktn_digitales-gelandemodell-dgm-osterreich

In Version 1.15.2 height of peaks is shown correct.
In Version 1.16.0 height of peaks are shown shifted app. 100 meters.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

I have tested it on different Win 10 computers and generate my VRTs again but this doesn't solve the problem.
After downgradig  to 1.15.2 problem was solved.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1.) Download 10m Digital Elevation Modell (DEM) from Austria
2.) Generate VRT and activate it
3.) Find peak e.q. Schneeberg/Klosterwappen in Lower Austria and put mouse cursor on it. (2075m should be displayed near peak)
4.) Repeat this for version 1.15.2 and 1.16.0 and you will see the 2075m point is shifted off peak app. 100m

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

The same height values should be displayed in 1.15.2 and 1.16.0

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

![1 16 0](https://user-images.githubusercontent.com/57573270/133960249-58af22bd-e7ea-4258-b770-6f922733789e.jpg)
![1 15 2](https://user-images.githubusercontent.com/57573270/133960252-60cb2792-6385-420d-981f-c035b4bf8036.jpg)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10
 - QMapShack Version:  1.16.0
 - Window Manager:  -

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
I guess this is a problem with the Proj8 installation. Probably some grid data is missing. If you find out what is missing we could ask the Windows package maintainer to add the data to the installer next time.

**Comment by mitxel-m** [comment]
I can confirm this behaviour on windows with QMS 1.15.2 and QMS 1.16.0, as mentioned by @konrad555.
I can also confirm the same displacement on linux with QMS 1.16.0dev with PROJ 8.
( Unfortunately these days I don't have the chance to tests in linux with a prior version of PROJ)

No doubt the change of PROJ version is bringing some problems. IMHO the origin of this issue seems to be the same to #430

In any case there is a workaround  that will let you use that DEM in QMS 1.16 with proj 8 for now.

__Workaround__ :  create a new VRT and manually indicate its SRS  

- In the case of the DEM for Austria we know that its SRS is EPSG:31287.
- Go to epsg.io to see details about EPSG:31287 -> https://epsg.io/31287 
- In this page we can get the definition of this SRS in PROJ4 format and copy it to the clipboard

`+proj=lcc +lat_1=49 +lat_2=46 +lat_0=47.5 +lon_0=13.333333333333333333333333 +x_0=400000 +y_0=400000 +ellps=bessel +towgs84=577,326,90,129,463,919,5,137,1,474,5,297,2,4232 +units=m +no_defs` 

(Note that includes a string +towgs84)

- In QMS: Create a new VRT with the VRT builder as usual, but in addition activate the advanced options and paste the string you have copied in the box for the -a_SRS option   

- The resulting VRT should appear in the correct place.

I have tested in QMS 1.16 with the Austrian DEM and it worked,  A nice way to check the result is to activate the "Elevation limit" option to color the areas above 2060m and check that it matches the base map.

- Don' match:
 
![](https://i.ibb.co/X8VQw9X/DHM10-ori.jpg)

- Match:

![](https://i.ibb.co/zNqc269/DHM10-tunned.jpg)

In this zip file there are both VRTs, the one created with any option, and the one created with the -a_SRS option. 
You can open both VRTs with a tex editor if you are curious about differences. -> [zip file](https://github.com/Maproom/qmapshack/files/7219038/AUSTRIA_DHM10_vrts.zip)

This is not a fix for the code, it is just a workaround, and the same procedure should be valid for any raster map wrapped in a VRT.  I hope it helps, although one never knows if having a workaround may demotivate the development of a better solution.

**Comment by kiozen** [comment]
I tested the EPSG:31287 projection with the built-in sanity check of QMapShack and found some peculiar behavior of the Proj8 API. I replaced the API by my own version. I can't tell if that helps please test. I won't merge this without testing.
https://github.com/Maproom/qmapshack/pull/442

I also filed a bug report at the Proj8 project
https://github.com/OSGeo/PROJ/issues/2866

**Comment by kiozen** [comment]
As the bug got fixed in Proj8 I assume that this one is fixed, too if compiled against the fixed Proj8 version. I close it for now.

**Comment by mitxel-m** [comment]
I have tested[ kiozens PR](https://github.com/Maproom/qmapshack/pull/442) and it solves the invalid latitude problem that occurred with some SRSs. The DEM is loaded, and also you can configure a grid for EPSG:31287, that seems to be ok.

However it does not solve the DEM shift mentioned in this issue. The DEM remains shifted and the grid appears shifted too.
So I don't expect the last fix in PROJ8 to solve this issue

In my opinion the shift is caused by the use of the exportToProj function which discouraged for PROJ8 and gdal 3, and it generates the shift only for some SRSs, while is working nice for  other ones. Reference in GDAL documentation, 
[here](https://gdal.org/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference13exportToProj4EPPc) and [here](https://gdal.org/api/ogr_srs_api.html#_CPPv416OSRExportToProj420OGRSpatialReferenceHPPc)

So I have been testing by replacing the exportToProj function by exportToWkt in CDemVRT.cpp and it worked.

**Here is a PR** :https://github.com/Maproom/qmapshack/pull/447

My coding skills are very limited, so this has to be taken with prudence, but I think that this could help to solve this issue.

**Notes:**
For get it working  you first have to get a Proj8 newer than 2021/09/26, which has already fixed the bug in PROJ8 reported by kiozen  \([reference here](https://github.com/OSGeo/PROJ/issues/2866) \) if not you get the 'invalid latitude' error.

As I couldn't get the latest version of PROJ8 and compile it, I tried it after merging the PR made by kiozen, which provides its own functions instead of the buggy PROJ ones.

I have also tested my PR with the current buggy version of PROJ8, and the rest of the VRT maps and DEMs I use are still working fine without changes. It would be good if someone else can test with other ones.


I have pull a similar PR for https://github.com/Maproom/qmapshack/issues/430

**Comment by mitxel-m** [comment]
Solved with PR #447

**Comment by konrad555** [comment]
@konrad555
