### ISSUE TITLE
Java version check fails in BRouter setup

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#594]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )

When setting up the BRouter configuration the java version is checked in `CRouterBRouterSetup::setJava` with a regular expression. This regular expression fails for Java 20 which shows the version on Windows in the following form:

~~~
java -version
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)
Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
~~~

The regular expression expects something of the form "20.99". Therefore, the check of the version fails and leads to a warning of the form `Your Java version %1 seems to be older than the required version %2. ...` 

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)

The given Java version should be accepted without a warning. This can be achieved by an appropriate modification of the used regular expression.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)

None

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)

The `BRouter will probably not work as expected` part of the warning message may discourage the user to use BRouter.

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)

None

**Comment by ntruchsess** [comment]
sure, will do

**Comment by ntruchsess** [comment]
fixed in #599

**Comment by ray66** [comment]
> @kiozen @wthaem fixed in #599

Version check fails with OpenJDK 17 when this PR is applied.

    >java -version
     OpenJDK Runtime Environment (build 17.0.9-ea+6-Debian-1)
    >java --version
     openjdk 17.0.9-ea 2023-10-17

**Comment by vincentxavier** [comment]
Same here, with 
```
❯ java -version
openjdk version "11.0.22-ea" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22-ea+6-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.22-ea+6-post-Debian-1, mixed mode, sharing)
```
Brouter work though 
```
❯ java -jar brouter-1.7.2-all.jar segments4/ 2 4 3 5 profiles2/fastbike.brf
BRouter 1.7.2 / 19072023
parsed profile profiles2/fastbike.brf cached=false
wp=182000000,94000000,from,0.0
wp=183000000,95000000,to,0.0
read referenceTrack, found=false dirty=false 
Error (linksProcessed=0 open paths: 0): datafile E0_N0.rd5 not found
expression cache stats=requests=0 requests2=0 cachemisses=0
NodesCache status before close=collecting=false noGhosts=false cacheSum=0 cacheSumClean=0 ghostSum=0 ghostWakeup=0
```

**Comment by diefau** [comment]
same under under Debian sid
> java -version
openjdk version "17.0.10-ea" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10-ea+6-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.10-ea+6-Debian-1, mixed mode, sharing)

or
> java --version
openjdk 17.0.10-ea 2024-01-16
OpenJDK Runtime Environment (build 17.0.10-ea+6-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.10-ea+6-Debian-1, mixed mode, sharing)

**Comment by kiozen** [comment]
@ntruchsess Think we still have a problem here. (Please fix in a new ticket)

Btw posting in a closed ticket is the safest way to miss the attention of developers.
